[providers]
providers = ["php"]

[variables]
NIXPACKS_PHP_VERSION = "8.2"
NIXPACKS_PHP_EXTENSIONS = "pdo_mysql, mbstring, bcmath, ctype, fileinfo, json, openssl, tokenizer, xml"

[phases.setup]
nixPkgs = ["...", "php82Extensions.pdo_mysql"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear"
]
